* Introducción a GitHub
** Videotutoriales
- [[https://youtu.be/SJf4iTkMNPo][Sesión 3.1]]
- [[https://youtu.be/GMH6hN8FKSU][Sesión 3.2]]
- [[https://youtu.be/5EJjRqtpqOM][Sesión 3.3]]
- [[https://youtu.be/A5PKw10PmNU][Sesión 3.4]]

** Índice
    - Breve descripción y posibilidades en la gestión de tareas del alumnado
    - Alternativas: GitLab, BitBucket,...
    - Cuentas
    - Configuración de la cuenta
    - Manejo básico de la plataforma
    - Repositorios: manejo y ajustes
    - Red social: comentarios, seguidores, etc.
    - Issues y Proyectos
    - Colaboración: Forks y Pull Requests
    - Organizaciones

** Referencias
- [[https://help.github.com/][Ayuda de GitHub]]
- [[https://help.github.com/articles/basic-writing-and-formatting-syntax/][Sintaxis de MarkDown]]
- [[https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account][Permisos de los colaboradores en un repositorio]]
- [[https://education.github.com/discount_requests/new][Solicitud de descuentos para uso educativo (repositorios privados gratuitos)]]
- [[https://help.github.com/articles/closing-issues-using-keywords/][Cerrar issues a través de mensajes en el commit]]

** Contenidos
- [[https://pedroprieto.github.io/curso-github/presentaciones/sesion-3-presentacion.html][Presentación]]
** Tareas
*** 1 - Creación de cuenta en GitHub
 1) Crea una cuenta en GitHub
 2) Añade tu dirección de correo de educación
 3) Solicita un descuento para uso educativo (ver enlace en apartado de Referencias)

*** 2 - Trabajo con repositorios, issues, forks y pull requests
 1) Haz un /fork/ del repositorio localizado en la siguiente url: [[https://github.com/curso-github-cefire/sesion3-practica]]
    1) Realiza un primer commit para poner tu nombre y apellidos en el fichero ~README.md~
    2) Crea 3 issues con los siguientes títulos:
       - Añadir 3 libros
       - Añadir 3 películas
       - Añadir 3 discos
    3) Crea una ~milestone~ denominada ~Tareas sesión 3-2~ que contenga los 3 issues creados.
    4) Modifica los ficheros correspondientes y realiza 3 commits para realizar cada una de las tareas que se indican en los issues. El mensaje del commit debe hacer que se cierren los issues correspondientes de manera automática.
    5) Haz una captura de pantalla de los comandos que has utilizado para hacer los commits y subir los cambios a GitHub.
    6) Incluye las capturas de pantalla en el repositorio dentro de la carpeta ~capturas~. Añádelas también al repositorio de manera que queden guardadas en tu repositorio en GitHub.
    7) Realiza una ~pull request~ indicando en el mensaje que has completado la tarea.

*** 3 - Trabajo con organizaciones
 1) Crea una organización en tu cuenta con el nombre ~organizacion-sesion-3~.
 2) Crea un repositorio dentro de la organización denominado ~sesion3-repo-organizacion~. Dicho repositorio debe contener:
    - Un archivo ~README~ con tu nombre y apellidos.
    - Un archivo ~.gitignore~ para el lenguaje ~Java~.
    - Un archivo de licencia de tipo ~MIT~.
 3) Crea un equipo dentro de la organización denominado ~equipo1~.
 4) Da permisos de escritura a ~equipo1~ en el repositorio creado.
 5) Invítame a formar parte de la organización y a formar parte del equipo ~equipo1~. Mi usuario de GitHub es ~pedroprieto~.

** Entrega de la tarea
No hay que subir ningún archivo en la tarea de la plataforma Moodle del Cefire.
